# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a44ce390e009e4372e847811af7dd5737b25892a2c057a2aa615b74e8318f0c90a4505e11e312d75d1988fb417449ed0f5a409e0ec8a365c02d961217f30f27

test:
  secret_key_base: 4d2d4e6e1a24b78934260b970b3cce988a806b5278030069d3041448c20f050b09ab6a7ce99c8c5ab63480832367c697f77a20dd6fe7e4955b8079e6fa0bcdf6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
